// <auto-generated />
using System;
using BasicBilling.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicBilling.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260308040551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 110.22m,
                            ClientId = 100,
                            Period = "202602",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 31.14m,
                            ClientId = 100,
                            Period = "202602",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 28.83m,
                            ClientId = 100,
                            Period = "202602",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 88.41m,
                            ClientId = 100,
                            Period = "202603",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 35.27m,
                            ClientId = 100,
                            Period = "202603",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 49.39m,
                            ClientId = 100,
                            Period = "202603",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 118.66m,
                            ClientId = 200,
                            Period = "202602",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 86.94m,
                            ClientId = 200,
                            Period = "202602",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 36.05m,
                            ClientId = 200,
                            Period = "202602",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 124.19m,
                            ClientId = 200,
                            Period = "202603",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 45.19m,
                            ClientId = 200,
                            Period = "202603",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 48.60m,
                            ClientId = 200,
                            Period = "202603",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 85.84m,
                            ClientId = 300,
                            Period = "202602",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 58.03m,
                            ClientId = 300,
                            Period = "202602",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 67.15m,
                            ClientId = 300,
                            Period = "202602",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 49.04m,
                            ClientId = 300,
                            Period = "202603",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 87.62m,
                            ClientId = 300,
                            Period = "202603",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 15.30m,
                            ClientId = 300,
                            Period = "202603",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 132.12m,
                            ClientId = 400,
                            Period = "202602",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 96.58m,
                            ClientId = 400,
                            Period = "202602",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 69.62m,
                            ClientId = 400,
                            Period = "202602",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 32.83m,
                            ClientId = 400,
                            Period = "202603",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 23.52m,
                            ClientId = 400,
                            Period = "202603",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 115.77m,
                            ClientId = 400,
                            Period = "202603",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 132.43m,
                            ClientId = 500,
                            Period = "202602",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 91.00m,
                            ClientId = 500,
                            Period = "202602",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 16.62m,
                            ClientId = 500,
                            Period = "202602",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 116.67m,
                            ClientId = 500,
                            Period = "202603",
                            ServiceType = "Water",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 32.16m,
                            ClientId = 500,
                            Period = "202603",
                            ServiceType = "Electricity",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 145.93m,
                            ClientId = 500,
                            Period = "202603",
                            ServiceType = "Sewer",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Joseph Carlton"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Maria Juarez"
                        },
                        new
                        {
                            Id = 300,
                            Name = "Albert Kenny"
                        },
                        new
                        {
                            Id = 400,
                            Name = "Jessica Phillips"
                        },
                        new
                        {
                            Id = 500,
                            Name = "Charles Johnson"
                        });
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Bill", b =>
                {
                    b.HasOne("BasicBilling.API.Domain.Entities.Client", "Client")
                        .WithMany("Bills")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BasicBilling.API.Domain.Entities.Bill", "Bill")
                        .WithOne("Payment")
                        .HasForeignKey("BasicBilling.API.Domain.Entities.Payment", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BasicBilling.API.Domain.Entities.Client", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
